input_channel: 3

# depth_multiple: 1.0
# width_multiple: 1.0

depth_multiple: 0.5
width_multiple: 0.5

backbone:
    # [repeat, module, args]
    [
        # [3, 'InvertedResidualv3', [5, 3.1, 40, 0, 0, 2]],
        # [3, 'Conv', [80, 1, 2, null, 1, 'Hardswish']],
        # [3, 'InvertedResidualv3', [5, 3.3, 64, 0, 1, 1]],
        # [3, 'InvertedResidualv3', [5, 2.9, 128, 0, 0, 2]],
        # [1, 'Conv', [640, 1, 1]],
        # [1, 'GlobalAvgPool', []],
        # [1, 'FixedConv', [6, 1, 1, null, 1, null]]

        # [1, 'DWConv', [32, 3, 1, null, 'ReLU']],
        # [1, 'Conv', [160, 5, 2, null, 1, 'ReLU']],
        # [2, 'InvertedResidualv3', [5, 3.0, 48, 1, 0, 1]],
        # [1, 'Conv', [1024, 1, 1]],
        # [1, 'GlobalAvgPool', []],
        # [1, 'FixedConv', [6, 1, 1, null, 1, null]]

        [2, 'DWConv', [32, 3, 1, null, 'ReLU']],
        [1, 'Conv', [144, 5, 2, null, 1, 'ReLU']],
        [2, 'InvertedResidualv3', [5, 3.1, 48, 0, 1, 1]],
        [1, 'Conv', [1024, 1, 1]],
        [1, 'GlobalAvgPool', []],
        [1, 'FixedConv', [6, 1, 1, null, 1, null]]

        # Conv argument: [out_channel, kernel_size, stride, padding_size]
        # if padding_size is not given or null, the padding_size will be auto adjusted as padding='SAME' in TensorFlow
        # [1, Conv, [16, 3, 2, null, 1, "HardSwish"]],
        # # k t c SE HS s
        # [1, InvertedResidualv3, [3, 1, 16, 0, 0, 1]],
        # [1, InvertedResidualv3, [3, 4, 24, 0, 0, 2]], # 2-P2/4, 24 # stride 1 for cifar, 2 for others
        # [1, InvertedResidualv3, [3, 3, 24, 0, 0, 1]],
        # [1, InvertedResidualv3, [5, 3, 40, 1, 0, 2]], # 4-P3/8, 40
        
        # [1, InvertedResidualv3, [5, 3, 40, 1, 0, 1]],
        # # [1, InvertedResidualv3, [5, 3, 40, 1, 0, 1]],
        # [1, InvertedResidualv3, [3, 6, 80, 0, 1, 2]], # 7-P4/16, 80
        # [1, InvertedResidualv3, [3, 2.5, 80, 0, 1, 1]],
        
        # [1, InvertedResidualv3, [3, 2.3, 80, 0, 1, 1]],
        # # [1, InvertedResidualv3, [3, 2.3, 80, 0, 1, 1]],
        
        # [1, InvertedResidualv3, [3, 6, 112, 1, 1, 1]],
        # # [1, InvertedResidualv3, [3, 6, 112, 1, 1, 1]], # 12 -P5/32, 112 
        # [1, InvertedResidualv3, [5, 6, 160, 1, 1, 2]],
        
        # [1, InvertedResidualv3, [5, 6, 160, 1, 1, 1]],
        # # [1, InvertedResidualv3, [5, 6, 160, 1, 1, 1]],
        
        # [1, Conv, [960, 1, 1]],
        # [1, GlobalAvgPool, []],
        # [1, Conv, [1280, 1, 1]],
        # [1, Flatten, []],
        # [1, Linear, [6]]
    ]